### ISSUE TITLE
Fatal error: /mnt/hhvm/index.hh appears to be a Hack file

### ISSUE THREAD

**Issue by preillyme** [nikolaplejic/docker.hhvm#1]
Fatal error: /mnt/hhvm/index.hh appears to be a Hack file, but you do not appear to be running the Hack typechecker. See the documentation at http://docs.hhvm.com/manual/en/install.hack.bootstrapping.php for information on getting it running. You can also set ````Hack.Lang.LookForTypechecker=0```` to disable this check (not recommended).

**Comment by nikolaplejic** [comment]
Hello Patrick,

I do believe your Pull Request #2 solved this issue. Sorry about the serious delay in closing it, and thanks for the PR! :)

-- Nikola
