### ISSUE TITLE
Building on Windows with boot2docker

### ISSUE THREAD

**Issue by ramvi** [nikolaplejic/docker.hhvm#5]
The ADDed run files get dos line breaks resulting in first these errors:

``` bash
docker@default:~$ docker run -t -p 80 hhvm
*** Running /etc/my_init.d/00_regen_ssh_host_keys.sh...
*** Running /etc/rc.local...
*** Booting runit daemon...
*** Runit started as PID 11
runsv nginx: fatal: unable to start ./run: file does not exist
runsv hhvm: fatal: unable to start ./run: file does not exist
```

Then this error when entering and running the scripts manually `bash: /etc/service/nginx/run: /bin/sh^M: bad interpreter: No such file or directory`

Opening both `run` files in `vi` and using the command `:set fileformat=unix` before saving, fixes the problem.

**Comment by nikolaplejic** [comment]
@ramvi Unfortunately, I don't have a Windows machine handy to test this out, but both `.sh` files do not seem to generate any diffs in Git when I try to re-save them with `:set fileformat=unix`. This sounds like something going bad during the process of copying these files into the Docker machine.

I will try to find a Windows/boot2docker machine to take a closer look at what's happening.
